import type { Deposit, KPIs, Mineral } from '../types';

export const MINERALS: Mineral[] = [
  { symbol:'Li',  name:'Lithium',      display_color:'#25f5a6', iea_critical:true },
  { symbol:'Cu',  name:'Copper',       display_color:'#ff7a22', iea_critical:true },
  { symbol:'Co',  name:'Cobalt',       display_color:'#3f8cff', iea_critical:true },
  { symbol:'Ni',  name:'Nickel',       display_color:'#27d8b2', iea_critical:true },
  { symbol:'REE', name:'Rare Earths',  display_color:'#a855f7', iea_critical:true },
  { symbol:'U',   name:'Uranium',      display_color:'#f6b93b', iea_critical:false },
  { symbol:'C',   name:'Graphite',     display_color:'#94a3b8', iea_critical:true },
  { symbol:'Mn',  name:'Manganese',    display_color:'#22d3ee', iea_critical:true },
];

export const MINERAL_COLOR: Record<string,string> = {
  Lithium:'#25f5a6', Copper:'#ff7a22', Cobalt:'#3f8cff',
  Nickel:'#27d8b2', 'Rare Earths':'#a855f7', Uranium:'#f6b93b',
  Graphite:'#94a3b8', Manganese:'#22d3ee', Tantalum:'#ffffff',
};

export const DEPOSITS: Deposit[] = [
  { id:'gb',  name:'Greenbushes Lithium Mine',     country:'Australia',       region:'Western Australia', latitude:-33.8536, longitude:116.0747, primary_mineral:'Lithium',    secondary_minerals:['Tantalum','Tin'],          deposit_type:'LCT Pegmatite',       status:'producing',   development_stage:'production',   resource_size_tonnes:286000000,  grade_percent:2.1,   grade_unit:'% Li₂O',  owner:'Talison (ALB/SQM/Tianqi)',  operator:'Talison Lithium',         opportunity_score:92, difficulty_score:34, underutilization_score:18, infrastructure_score:95, country_risk_score:12, environmental_risk_score:28, data_confidence:'high',   mineral_color:'#10b981', source_count:18, paleo_setting:'Paleoproterozoic Balingup Metamorphic Belt, Yilgarn Craton', ai_summary:"World's largest high-grade lithium mine. 286Mt @ 2.1% Li₂O. CGP3 expansion commissioning 2025. Near fully utilised — benchmark asset.", flags:['high_priority','world_class'] },
  { id:'at',  name:'Salar de Atacama',             country:'Chile',           region:'Antofagasta',       latitude:-23.4833, longitude:-68.2667, primary_mineral:'Lithium',    secondary_minerals:['Potassium','Boron'],       deposit_type:'Brine (Salar)',        status:'producing',   development_stage:'production',   resource_size_tonnes:9800000000, grade_percent:0.157, grade_unit:'% Li',    owner:'SQM / Albemarle',           operator:'SQM / Albemarle',         opportunity_score:91, difficulty_score:38, underutilization_score:14, infrastructure_score:72, country_risk_score:28, environmental_risk_score:68, data_confidence:'high',   mineral_color:'#10b981', source_count:14, paleo_setting:'Neogene closed-basin brine system, Atacama Basin, Andean volcanic arc', ai_summary:"World's largest lithium brine operation. Highest grade globally. Key risk: water usage in hyperarid environment and indigenous water rights.", flags:['world_class','water_risk'] },
  { id:'esc', name:'Escondida',                    country:'Chile',           region:'Antofagasta',       latitude:-24.2667, longitude:-69.0667, primary_mineral:'Copper',     secondary_minerals:['Gold','Silver','Molybdenum'], deposit_type:'Porphyry Copper',   status:'producing',   development_stage:'production',   resource_size_tonnes:32400000000,grade_percent:0.44,  grade_unit:'%',       owner:'BHP 57.5% / Rio Tinto 30%', operator:'BHP Billiton Minerals',   opportunity_score:89, difficulty_score:30, underutilization_score:12, infrastructure_score:80, country_risk_score:28, environmental_risk_score:42, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:12, paleo_setting:'Paleocene-Eocene Domeyko Cordillera porphyry belt', ai_summary:"World's largest copper mine ~5% global supply. Sulphide and oxide ore, SX-EW plant. Desalination water supply at Coloso.", flags:['world_class','high_priority'] },
  { id:'tf',  name:'Tenke Fungurume',              country:'DR Congo',        region:'Lualaba Province',  latitude:-10.5833, longitude:26.1167,  primary_mineral:'Cobalt',     secondary_minerals:['Copper'],                  deposit_type:'Sediment-Hosted (SEDEX)', status:'producing', development_stage:'production',  resource_size_tonnes:1450000000, grade_percent:0.38,  grade_unit:'% Co',    owner:'CMOC 80% / Gécamines 20%',  operator:'CMOC Group',              opportunity_score:85, difficulty_score:72, underutilization_score:22, infrastructure_score:38, country_risk_score:88, environmental_risk_score:55, data_confidence:'high',   mineral_color:'#3b82f6', source_count:9,  paleo_setting:'Neoproterozoic Katangan Basin, Central African Copperbelt', ai_summary:"High-grade cobalt. CMOC acquired from Freeport 2016. DRC political risk and export levy disputes persistent. Critical to global battery cobalt.", flags:['country_risk_flag','cobalt_critical'] },
  { id:'by',  name:'Bayan Obo REE Mine',           country:'China',           region:'Inner Mongolia',    latitude:41.8014,  longitude:109.9742, primary_mineral:'Rare Earths', secondary_minerals:['Iron','Niobium'],          deposit_type:'Carbonatite',         status:'producing',   development_stage:'production',   resource_size_tonnes:1500000000, grade_percent:6.2,   grade_unit:'% REO',   owner:'Baogang Group (state)',     operator:'Baotou Steel (Baogang)',  opportunity_score:87, difficulty_score:55, underutilization_score:30, infrastructure_score:85, country_risk_score:45, environmental_risk_score:60, data_confidence:'medium', mineral_color:'#8b5cf6', source_count:7,  paleo_setting:'Proterozoic North China Craton margin, carbonatite-associated', ai_summary:"World's largest REE deposit. Supplies ~60% of global rare earth output. State-controlled. Thorium radioactive tailings a significant liability.", flags:['geopolitical_risk','world_class'] },
  { id:'od',  name:'Olympic Dam',                  country:'Australia',       region:'South Australia',   latitude:-30.4436, longitude:136.8861, primary_mineral:'Copper',     secondary_minerals:['Uranium','Gold','Silver','REE'], deposit_type:'IOCG',          status:'producing',   development_stage:'expansion',    resource_size_tonnes:10100000000,grade_percent:0.72,  grade_unit:'%',       owner:'BHP',                       operator:'BHP',                     opportunity_score:86, difficulty_score:48, underutilization_score:55, infrastructure_score:70, country_risk_score:12, environmental_risk_score:35, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:11, paleo_setting:'Mesoproterozoic Gawler Craton IOCG ~1.59 Ga Hiltaba Suite', ai_summary:"World's largest uranium deposit and 4th largest copper. BHP expansion targets 650ktpa Cu. 60km purpose-built rail to Port Augusta.", flags:['world_class','expansion_potential'] },
  { id:'pil', name:'Pilgangoora',                  country:'Australia',       region:'Western Australia', latitude:-21.3333, longitude:118.6833, primary_mineral:'Lithium',    secondary_minerals:['Tantalum'],                deposit_type:'LCT Pegmatite',       status:'producing',   development_stage:'expansion',    resource_size_tonnes:308000000,  grade_percent:1.13,  grade_unit:'% Li₂O',  owner:'Pilbara Minerals (ASX:PLS)',operator:'Pilbara Minerals',        opportunity_score:82, difficulty_score:35, underutilization_score:38, infrastructure_score:80, country_risk_score:12, environmental_risk_score:22, data_confidence:'high',   mineral_color:'#10b981', source_count:8,  paleo_setting:'Archean Pilbara Craton metasediment-hosted LCT pegmatite suite', ai_summary:"One of world's largest hard rock lithium deposits. P1000 expansion to 1Mtpa underway. ~200km to Port Hedland.", flags:['expansion_potential'] },
  { id:'su',  name:'Sudbury Basin',                country:'Canada',          region:'Ontario',           latitude:46.5000,  longitude:-81.0000, primary_mineral:'Nickel',     secondary_minerals:['Copper','Cobalt','PGMs'],  deposit_type:'Magmatic Sulphide',   status:'producing',   development_stage:'production',   resource_size_tonnes:1800000000, grade_percent:1.3,   grade_unit:'% Ni',    owner:'Glencore/Vale/KGHM',        operator:'Multiple operators',      opportunity_score:80, difficulty_score:40, underutilization_score:20, infrastructure_score:88, country_risk_score:10, environmental_risk_score:35, data_confidence:'high',   mineral_color:'#14b8a6', source_count:15, paleo_setting:'1.85 Ga Sudbury Igneous Complex — meteorite impact melt sheet, Superior Province', ai_summary:"World's largest nickel sulphide camp. 140+ years production. Multiple operators. PGM byproduct significant. Excellent jurisdiction.", flags:['world_class','mature_district'] },
  { id:'cj',  name:'Carajás Province',             country:'Brazil',          region:'Pará State',        latitude:-6.0667,  longitude:-50.1833, primary_mineral:'Copper',     secondary_minerals:['Nickel','Iron','Gold'],    deposit_type:'IOCG / BIF',          status:'producing',   development_stage:'production',   resource_size_tonnes:7200000000, grade_percent:0.92,  grade_unit:'%',       owner:'Vale S.A.',                 operator:'Vale S.A.',               opportunity_score:84, difficulty_score:42, underutilization_score:28, infrastructure_score:72, country_risk_score:35, environmental_risk_score:48, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:10, paleo_setting:'Archean Carajás Domain, Amazon Craton — Neoarchean IOCG hydrothermal system', ai_summary:"World's most significant mineral province — highest-grade iron, major copper (Sossego/Salobo), nickel (Onça Puma). Amazon logistics complexity.", flags:['world_class','multi_mineral'] },
  { id:'kol', name:'Kolwezi Copper-Cobalt District',country:'DR Congo',       region:'Lualaba Province',  latitude:-10.7167, longitude:25.4667,  primary_mineral:'Cobalt',     secondary_minerals:['Copper'],                  deposit_type:'SEDEX / Sediment-Hosted', status:'producing', development_stage:'production',  resource_size_tonnes:2800000000, grade_percent:0.65,  grade_unit:'% Co',    owner:'Glencore dominant',         operator:'Glencore / multiple',     opportunity_score:83, difficulty_score:78, underutilization_score:28, infrastructure_score:35, country_risk_score:90, environmental_risk_score:58, data_confidence:'medium', mineral_color:'#3b82f6', source_count:8,  paleo_setting:'Neoproterozoic Katangan Copperbelt stratabound sulphide, Roan Group', ai_summary:"Kolwezi district encompasses multiple operations. ASM overlap creates human rights due diligence burden. Highest country risk in database.", flags:['country_risk_flag','asm_overlap','cobalt_critical'] },
  { id:'th',  name:'Thacker Pass',                 country:'United States',   region:'Nevada',            latitude:41.8483,  longitude:-118.0594,primary_mineral:'Lithium',    secondary_minerals:['Sulphur'],                 deposit_type:'Sedimentary Claystone',status:'construction',development_stage:'construction',resource_size_tonnes:13700000,   grade_percent:0.35,  grade_unit:'% Li',    owner:'Lithium Americas / GM',     operator:'Lithium Americas Corp',   opportunity_score:76, difficulty_score:55, underutilization_score:72, infrastructure_score:65, country_risk_score:8,  environmental_risk_score:58, data_confidence:'high',   mineral_color:'#10b981', source_count:7,  paleo_setting:'Miocene McDermitt Caldera lacustrine sedimentary basin — volcanic ash-derived Li smectite', ai_summary:"Largest known lithium resource in the USA. GM $650M investment. Novel acid-leach clay process unproven at scale. Indigenous Paiute-Shoshone site contested.", flags:['construction_stage','indigenous_rights','strategic_usa'] },
  { id:'cv',  name:'Cerro Verde',                  country:'Peru',            region:'Arequipa',          latitude:-16.5333, longitude:-71.5500, primary_mineral:'Copper',     secondary_minerals:['Molybdenum','Silver'],     deposit_type:'Porphyry Copper',     status:'producing',   development_stage:'production',   resource_size_tonnes:4800000000, grade_percent:0.37,  grade_unit:'%',       owner:'Freeport 53.6% / Sumitomo 21%', operator:'Freeport-McMoRan',    opportunity_score:79, difficulty_score:48, underutilization_score:22, infrastructure_score:75, country_risk_score:42, environmental_risk_score:38, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:8,  paleo_setting:'Miocene Coastal Batholith, Andean Cordillera Occidental porphyry province', ai_summary:"Peru's largest copper operation. 360ktpd throughput since 2015 expansion. Water scarcity and Arequipa community relations are primary risks.", flags:['high_priority'] },
  { id:'mn',  name:'Manono Lithium Project',        country:'DR Congo',        region:'Tanganyika Province',latitude:-7.3000, longitude:27.4167,  primary_mineral:'Lithium',    secondary_minerals:['Tin','Tantalum','Niobium'],deposit_type:'LCT Pegmatite',      status:'exploration', development_stage:'pre_feasibility',resource_size_tonnes:401000000, grade_percent:1.65,  grade_unit:'% Li₂O',  owner:'AVZ Minerals (disputed)',   operator:'AVZ / Zijin (contested)', opportunity_score:70, difficulty_score:90, underutilization_score:95, infrastructure_score:15, country_risk_score:95, environmental_risk_score:45, data_confidence:'medium', mineral_color:'#10b981', source_count:4,  paleo_setting:'Proterozoic Kibaran Belt — LCT spodumene pegmatite', ai_summary:"Potentially world's largest hard rock Li resource. Active ownership dispute. 3000km from nearest port, no paved road, no grid power. Textbook high-opportunity, extreme-difficulty asset.", flags:['ownership_dispute','country_risk_flag','infrastructure_critical'] },
  { id:'jb',  name:'James Bay Lithium (CV5)',       country:'Canada',          region:'Québec',            latitude:52.2833,  longitude:-76.6000, primary_mineral:'Lithium',    secondary_minerals:['Tantalum'],                deposit_type:'LCT Pegmatite',       status:'exploration', development_stage:'advanced_exploration', resource_size_tonnes:109000000, grade_percent:1.4, grade_unit:'% Li₂O', owner:'Patriot Battery Metals', operator:'Patriot Battery Metals',   opportunity_score:73, difficulty_score:52, underutilization_score:88, infrastructure_score:40, country_risk_score:8,  environmental_risk_score:38, data_confidence:'medium', mineral_color:'#10b981', source_count:5,  paleo_setting:'Archean Superior Province — Auclair Formation metaturbidite-hosted pegmatite swarm', ai_summary:"Major 2022 discovery (CV5 pegmatite). Exceptional intercepts. Remote northern Québec — ice road access only. Cree Nation consultation ongoing.", flags:['recent_discovery','high_grade','expansion_potential'] },
  { id:'mh',  name:'Mount Holland (Covalent)',      country:'Australia',       region:'Western Australia', latitude:-32.1833, longitude:119.5500, primary_mineral:'Lithium',    secondary_minerals:['Tantalum'],                deposit_type:'LCT Pegmatite',       status:'construction',development_stage:'construction',resource_size_tonnes:189000000,  grade_percent:1.5,   grade_unit:'% Li₂O',  owner:'SQM 50% / Wesfarmers 50%', operator:'Covalent Lithium JV',    opportunity_score:78, difficulty_score:40, underutilization_score:62, infrastructure_score:72, country_risk_score:12, environmental_risk_score:25, data_confidence:'high',   mineral_color:'#10b981', source_count:6,  paleo_setting:'Archean Yilgarn Craton — Earl Grey spodumene pegmatite in gneissic country rock', ai_summary:"Major Li deposit in construction. Integrated mine-to-refinery model with Kwinana LiOH plant. High underutilization as refinery commissioning delayed.", flags:['construction_stage','integrated_refinery'] },
  { id:'kv',  name:'Kevitsa Mine',                  country:'Finland',         region:'Lapland',           latitude:67.7400,  longitude:26.6900,  primary_mineral:'Nickel',     secondary_minerals:['Copper','Cobalt','PGMs'],  deposit_type:'Magmatic Sulphide',   status:'producing',   development_stage:'production',   resource_size_tonnes:500000000,  grade_percent:0.25,  grade_unit:'% Ni',    owner:'Boliden AB',                operator:'Boliden AB',              opportunity_score:72, difficulty_score:38, underutilization_score:30, infrastructure_score:75, country_risk_score:5,  environmental_risk_score:42, data_confidence:'high',   mineral_color:'#14b8a6', source_count:7,  paleo_setting:'Paleoproterozoic Central Lapland Greenstone Belt — mafic-ultramafic Ni-Cu-PGE', ai_summary:"Important European battery Ni + Co source. AAA jurisdiction (Finland, EU member). Arctic logistics well-serviced by Finnish infrastructure.", flags:['european_supply_chain','eu_strategic'] },
  { id:'ka',  name:'Kansanshi Mine',                country:'Zambia',          region:'North-Western Province', latitude:-12.0667, longitude:25.8833, primary_mineral:'Copper',  secondary_minerals:['Gold'],                    deposit_type:'Sediment-Hosted / Skarn', status:'producing', development_stage:'expansion',  resource_size_tonnes:3900000000, grade_percent:0.68,  grade_unit:'%',       owner:'First Quantum 80% / ZCCM 20%', operator:'First Quantum Minerals', opportunity_score:77, difficulty_score:55, underutilization_score:25, infrastructure_score:58, country_risk_score:60, environmental_risk_score:35, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:9,  paleo_setting:'Neoproterozoic Zambian Copperbelt — Katangan Basin ore shale', ai_summary:"Africa's largest copper mine by production. S3 expansion adding 150ktpa. FQM faces ongoing royalty and taxation disputes with Zambia government.", flags:['expansion_potential','country_risk_flag'] },
  { id:'ri',  name:'Rincón Lithium Project',        country:'Argentina',       region:'Salta Province',    latitude:-23.7000, longitude:-67.3000, primary_mineral:'Lithium',    secondary_minerals:['Potassium'],               deposit_type:'Brine (Salar)',        status:'construction',development_stage:'construction',resource_size_tonnes:4600000,    grade_percent:0.048, grade_unit:'% Li',    owner:'Rio Tinto',                 operator:'Rio Tinto',               opportunity_score:73, difficulty_score:52, underutilization_score:60, infrastructure_score:45, country_risk_score:55, environmental_risk_score:52, data_confidence:'medium', mineral_color:'#10b981', source_count:5,  paleo_setting:'Puna Plateau Neogene closed-basin salar — southern Lithium Triangle', ai_summary:"Rio Tinto acquired for $825M in 2022 — first major miner direct entry into lithium brine. Pilot plant 2024. Full DFS underway.", flags:['construction_stage','major_miner_entry','lithium_triangle'] },
  { id:'co',  name:'Cauchari-Olaroz Salar',         country:'Argentina',       region:'Jujuy Province',    latitude:-23.3500, longitude:-66.8000, primary_mineral:'Lithium',    secondary_minerals:['Potassium'],               deposit_type:'Brine (Salar)',        status:'producing',   development_stage:'production',   resource_size_tonnes:19300000,   grade_percent:0.062, grade_unit:'% Li',    owner:'Lithium Americas 44.8% / Ganfeng 46.7%', operator:'Lithium Americas AR', opportunity_score:74, difficulty_score:50, underutilization_score:45, infrastructure_score:50, country_risk_score:55, environmental_risk_score:55, data_confidence:'medium', mineral_color:'#10b981', source_count:6,  paleo_setting:'Puna Plateau Neogene closed-basin salar — Northern Lithium Triangle', ai_summary:"First production 2023. Phase 1 targets 40ktpa LCE. Ganfeng as Chinese strategic partner. Lithium Americas split NA/SA businesses 2023.", flags:['recently_commissioned','lithium_triangle'] },
  { id:'qb',  name:'Quebrada Blanca Phase 2',       country:'Chile',           region:'Tarapacá Region',   latitude:-21.0667, longitude:-68.8333, primary_mineral:'Copper',     secondary_minerals:['Molybdenum','Silver'],     deposit_type:'Porphyry Copper',     status:'producing',   development_stage:'production',   resource_size_tonnes:6900000000, grade_percent:0.55,  grade_unit:'%',       owner:'Teck 60% / Sumitomo 30%',   operator:'Teck QB2',                opportunity_score:80, difficulty_score:45, underutilization_score:42, infrastructure_score:65, country_risk_score:28, environmental_risk_score:50, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:8,  paleo_setting:'Eocene-Oligocene Precordilleran porphyry belt, 4400m elevation', ai_summary:"QB2 commissioned 2023. One of the largest Cu projects brought to production this decade. High altitude (4400m) adds complexity.", flags:['recently_commissioned'] },
  { id:'ak',  name:'Aktogay Mine',                  country:'Kazakhstan',      region:'East Kazakhstan',   latitude:46.8500,  longitude:79.3167,  primary_mineral:'Copper',     secondary_minerals:['Molybdenum'],              deposit_type:'Porphyry Copper',     status:'producing',   development_stage:'production',   resource_size_tonnes:5800000000, grade_percent:0.33,  grade_unit:'%',       owner:'KAZ Minerals',              operator:'KAZ Minerals',            opportunity_score:74, difficulty_score:58, underutilization_score:35, infrastructure_score:60, country_risk_score:55, environmental_risk_score:32, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:7,  paleo_setting:'Paleozoic Central Asian Orogenic Belt — Devonian porphyry province', ai_summary:"Major Central Asia porphyry Cu. Phase 2 expansion doubles capacity ~200ktpa. KAZ Minerals taken private by Cuprum Holding 2021.", flags:['expansion_completed'] },
  { id:'jc',  name:'Jinchuan Nickel Deposit',       country:'China',           region:'Gansu Province',    latitude:38.5286,  longitude:102.1836, primary_mineral:'Nickel',     secondary_minerals:['Copper','Cobalt','PGMs'],  deposit_type:'Magmatic Sulphide',   status:'producing',   development_stage:'production',   resource_size_tonnes:500000000,  grade_percent:1.02,  grade_unit:'% Ni',    owner:'Jinchuan Group (state)',    operator:'Jinchuan Group',          opportunity_score:75, difficulty_score:50, underutilization_score:25, infrastructure_score:80, country_risk_score:45, environmental_risk_score:40, data_confidence:'medium', mineral_color:'#14b8a6', source_count:5,  paleo_setting:'Proterozoic North China Craton — mafic-ultramafic Ni-Cu sulphide', ai_summary:"World's 3rd largest Ni sulphide deposit. State-owned. Strong domestic processing. Limited Western investment access. PGM byproduct.", flags:['state_controlled','geopolitical_risk'] },
  { id:'sg',  name:'Sierra Gorda',                  country:'Chile',           region:'Antofagasta',       latitude:-22.8667, longitude:-69.3167, primary_mineral:'Copper',     secondary_minerals:['Molybdenum','Silver'],     deposit_type:'Porphyry Copper',     status:'producing',   development_stage:'production',   resource_size_tonnes:3900000000, grade_percent:0.42,  grade_unit:'%',       owner:'KGHM 55% / Sumitomo 45%',  operator:'KGHM International',     opportunity_score:73, difficulty_score:42, underutilization_score:35, infrastructure_score:72, country_risk_score:28, environmental_risk_score:38, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:6,  paleo_setting:'Eocene Cordillera Domeyko porphyry belt — same province as Escondida', ai_summary:"KGHM's Chile flagship. Consistent producer in Antofagasta porphyry belt. Molybdenum byproduct significant at current prices.", flags:['andean_porphyry'] },
  { id:'dk',  name:'Danakhil Potash Project',       country:'Ethiopia',        region:'Afar Region',       latitude:13.4667,  longitude:40.6167,  primary_mineral:'Uranium',    secondary_minerals:['Potash','Borate'],         deposit_type:'Evaporite Basin',     status:'exploration', development_stage:'feasibility',  resource_size_tonnes:11000000000,grade_percent:32.0,  grade_unit:'% K₂O',   owner:'Circum Minerals (contested)', operator:'Circum Minerals',       opportunity_score:65, difficulty_score:85, underutilization_score:90, infrastructure_score:18, country_risk_score:80, environmental_risk_score:60, data_confidence:'low',    mineral_color:'#f59e0b', source_count:3,  paleo_setting:'Afar Rift System — Neogene extensional rift evaporite, Danakil Depression -120m', ai_summary:"Enormous high-grade potash deposit. Danakil Depression — hottest inhabited place on Earth. Tigray conflict 2020-2022 disrupted operations. Ownership contested.", flags:['extreme_environment','conflict_affected','data_gap'] },
  { id:'sb',  name:'Sossego-Sequeirinho',           country:'Brazil',          region:'Pará State',        latitude:-6.3667,  longitude:-50.6833, primary_mineral:'Copper',     secondary_minerals:['Gold'],                    deposit_type:'IOCG',                status:'producing',   development_stage:'production',   resource_size_tonnes:890000000,  grade_percent:0.72,  grade_unit:'%',       owner:'Vale S.A.',                 operator:'Vale S.A.',               opportunity_score:74, difficulty_score:45, underutilization_score:35, infrastructure_score:68, country_risk_score:35, environmental_risk_score:45, data_confidence:'high',   mineral_color:'#cd7c3f', source_count:6,  paleo_setting:'Carajás Domain IOCG system — Archean Amazon Craton', ai_summary:"Vale's primary copper mine in Carajás. IOCG system with Au byproduct. Significant infrastructure investment in remote Amazon region.", flags:[] },
  { id:'lo',  name:'Lohia Nickel Belt',             country:'Indonesia',       region:'Sulawesi',          latitude:-2.5000,  longitude:121.5000, primary_mineral:'Nickel',     secondary_minerals:['Cobalt'],                  deposit_type:'Laterite',            status:'producing',   development_stage:'production',   resource_size_tonnes:800000000,  grade_percent:1.1,   grade_unit:'% Ni',    owner:'Vale Indonesia / Nickel Industries', operator:'Multiple',     opportunity_score:76, difficulty_score:48, underutilization_score:40, infrastructure_score:55, country_risk_score:45, environmental_risk_score:65, data_confidence:'medium', mineral_color:'#14b8a6', source_count:5,  paleo_setting:'Ophiolite-hosted laterite profile, Sulawesi ophiolite belt', ai_summary:"Indonesia holds world's largest nickel reserves. Sulawesi laterite operations support EV supply chain. Processing HPAL plants under development.", flags:['ev_supply_chain','nickel_critical'] },
  { id:'ken', name:'Kenticha Lithium-Tantalum',     country:'Ethiopia',        region:'Oromia Region',     latitude:5.5800,   longitude:39.7300,  primary_mineral:'Lithium',    secondary_minerals:['Tantalum'],                deposit_type:'LCT Pegmatite',       status:'exploration', development_stage:'feasibility',  resource_size_tonnes:45000000,   grade_percent:1.08,  grade_unit:'% Li₂O',  owner:'EMDSC (state)',             operator:'Ethiopian Min. Dev. Corp', opportunity_score:70, difficulty_score:63, underutilization_score:82, infrastructure_score:32, country_risk_score:65, environmental_risk_score:42, data_confidence:'medium', mineral_color:'#25f5a6', source_count:4,  paleo_setting:'Mozambique Belt Neoproterozoic pegmatite province — East African Orogen, collision-related LCT pegmatites', ai_summary:"Pegmatite-hosted lithium and tantalum potential offers regional growth optionality. Infrastructure, resource definition, and financing depth will determine development velocity.", flags:['underutilized','east_africa','regional_growth'] },
];

export function computeKPIs(deposits: Deposit[]): KPIs {
  const total = deposits.length;
  const producing = deposits.filter(d => d.status === 'producing').length;
  const undeveloped = deposits.filter(d => ['undeveloped','exploration','feasibility'].includes(d.status)).length;
  const countries = new Set(deposits.map(d => d.country)).size;
  const minerals = new Set(deposits.map(d => d.primary_mineral)).size;
  const highOpp = deposits.filter(d => d.opportunity_score >= 75).length;
  const highConf = deposits.filter(d => d.data_confidence === 'high').length;
  const avgOpp = Math.round(deposits.reduce((s,d) => s + d.opportunity_score, 0) / total);
  return { total_deposits:total, producing, undeveloped, countries_covered:countries, minerals_covered:minerals, high_opportunity:highOpp, high_confidence:highConf, avg_opportunity:avgOpp };
}
